USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_DIM_VEICULO (@DATA_CARGA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	SET LANGUAGE BRAZILIAN 

	INSERT INTO DIM_VEICULO (COD_VEICULO, RENAVAM, PLACA, DATA_EMISSAO, EXPEDIDOR, ESTADO) 
	SELECT COD_VEICULO, RENAVAM, PLACA, DATA_EMISSAO, EXPEDIDOR, ESTADO
	FROM TB_AUX_VEICULO
	WHERE DATA_CARGA = @DATA_CARGA

	UPDATE DIM_VEICULO
	SET COD_VEICULO = VE.COD_VEICULO,
		RENAVAM = VE.RENAVAM,
		PLACA = VE.PLACA, 
		DATA_EMISSAO = VE.DATA_EMISSAO,
		EXPEDIDOR = VE.EXPEDIDOR,
		ESTADO = VE.ESTADO
	FROM DIM_VEICULO DV INNER JOIN TB_AUX_VEICULO VE
	ON DV.COD_VEICULO = VE.COD_VEICULO 
END

EXEC SP_DIM_VEICULO '20230320'

SELECT * FROM TB_AUX_VEICULO
SELECT * FROM DIM_VEICULO