USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_DIM_STATUS (@DATA_CARGA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	SET LANGUAGE BRAZILIAN 

	INSERT INTO DIM_STATUS (STATUS, COD_STATUS_VIAGEM) 
	SELECT STATUS, COD_STATUS
	FROM TB_AUX_STATUS
	WHERE DATA_CARGA = @DATA_CARGA

	UPDATE DIM_STATUS
	SET STATUS = S.STATUS,
		COD_STATUS_VIAGEM = S.COD_STATUS
	FROM DIM_STATUS DS INNER JOIN TB_AUX_STATUS S
	ON DS.COD_STATUS_VIAGEM = S.COD_STATUS
END

EXEC SP_DIM_STATUS '20240320'

SELECT * FROM DIM_STATUS