USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_FATO_VIAGEM (@DATA_CARGA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	SET LANGUAGE BRAZILIAN

	INSERT INTO FATO_VIAGEM(ID_LOCAL_ORIGEM, ID_LOCAL_DESTINO, ID_STATUS, ID_MOTORISTA, ID_DATA_PARTIDA, ID_DATA_CHEGADA,ID_DATA_DISPONIVEL, QUANTIDADE_DE_VAGAS, VALOR)
	SELECT DLO.ID_LOCAL, DLD.ID_LOCAL, DS.ID_STATUS, DM.ID_MOTORISTA, DTP.ID_TEMPO, DTC.ID_TEMPO, DTD.ID_TEMPO, AV.TOTAL_VAGAS, AV.VALOR_PASSAGEM
	FROM TB_AUX_VIAGEM AV INNER JOIN DIM_LOCAL DLO
	ON AV.LOCAL_ORIGEM = DL.LOCAL 
	INNER JOIN DIM_LOCAL DLD
	ON AV.LOCAL_DESTINO = DL.LOCAL
	INNER JOIN DIM_STATUS DS
	ON AV.STATUS = DS.STATUS
        INNER JOIN DIM_MOTORISTA DM
        ON AV.COD_MOTORISTA = DM.COD_MOTORISTA
        INNER JOIN DIM_TEMPO DTP
        ON AV.DATA_PARTIDA = DTP.DATA
        INNER JOIN DIM_TEMPO DTP
        ON AV.DATA_DATA_CHEGADA = DTC.DATA
        INNER JOIN DIM_TEMPO DTD
        ON AV.DATA_DISPONIVEL = DTD.DATA
        WHERE AV.DATA_CARGA = @DATA_CARGA
        GROUP BY DLO.ID_LOCAL, DLD.ID_LOCAL, DS.ID_STATUS, DM.ID_MOTORISTA, DTP.ID_TEMPO, DTC.ID_TEMPO, DTD.ID_TEMPO, AV.TOTAL_VAGAS, AV.VALOR_PASSAGEM
END

SELECT * FROM FATO_VIAGEM
SELECT * FROM TB_AUX_VIAGEM
SELECT * FROM DIM_MOTORISTA
SELECT * FROM DIM_LOCAL
SELECT * FROM DIM_TEMPO
SELECT * FROM DIM_STATUS

