USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_OLTP_VIAGEM (@DATA_CARGA DATETIME, @DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
    SET NOCOUNT ON
    SET LANGUAGE BRAZILIAN

    DELETE FROM TB_AUX_VIAGEM
    WHERE DATA_CARGA = @DATA_CARGA

    INSERT INTO TB_AUX_VIAGEM 
    SELECT @DATA_CARGA, TITULO, LOCAL_ORIGEM, LOCAL_DESTINO, VALOR_PASSAGEM, TOTAL_VAGAS, DATA_PARTIDA, DATA_CHEGADA, 
            DATA_DISPONIVEL, DESCRICAO, 
            CASE STATUS
                WHEN 'DISPONIVEL' THEN 1
                WHEN 'CONFIRMADA' THEN 2
                WHEN 'CONCLUIDA' THEN 3
                WHEN 'CANCELADA' THEN 4
            END,
            COD_MOTORISTA
    FROM TB_VIAGEM V
    WHERE DATA_PARTIDA BETWEEN @DATA_INICIAL AND @DATA_FINAL
    AND NOT EXISTS (
        SELECT 1 
        FROM TB_VIO_VIAGEM 
        WHERE DATA_CARGA = @DATA_CARGA
        AND TITULO = V.TITULO
        AND LOCAL_ORIGEM = V.LOCAL_ORIGEM
        AND LOCAL_DESTINO = V.LOCAL_DESTINO
        AND VALOR_PASSAGEM = V.VALOR_PASSAGEM
        AND TOTAL_VAGAS = V.TOTAL_VAGAS
        AND DATA_PARTIDA = V.DATA_PARTIDA
        AND DATA_CHEGADA = V.DATA_CHEGADA
        AND DATA_DISPONIVEL = V.DATA_DISPONIVEL
        AND DESCRICAO = V.DESCRICAO
        AND COD_STATUS = (
            CASE V.STATUS
                WHEN 'DISPONIVEL' THEN 1
                WHEN 'CONFIRMADA' THEN 2
                WHEN 'CONCLUIDA' THEN 3
                WHEN 'CANCELADA' THEN 4
            END)
        AND COD_MOTORISTA = V.COD_MOTORISTA
    )

    SET @DATA_INICIAL = @DATA_INICIAL + 1
END

EXEC SP_OLTP_VIAGEM '20240322', '20230101', '20240101'

SELECT * FROM TB_AUX_VIAGEM

SELECT * FROM TB_VIO_VIAGEM