USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_OLTP_VIAGEM (@DATA_CARGA DATETIME, @DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
    SET NOCOUNT ON
    SET LANGUAGE BRAZILIAN

    DELETE FROM TB_AUX_VIAGEM
    WHERE DATA_CARGA = @DATA_CARGA

    INSERT INTO TB_AUX_VIAGEM 
    SELECT @DATA_CARGA, TITULO, LOCAL_ORIGEM, LOCAL_DESTINO, VALOR_PASSAGEM, TOTAL_VAGAS, DATA_PARTIDA, DATA_CHEGADA, 
            DATA_DISPONIVEL, DESCRICAO, 
            CASE STATUS
                WHEN 'DISPONIVEL' THEN 1
                WHEN 'CONFIRMADA' THEN 2
                WHEN 'CONCLUIDA' THEN 3
                WHEN 'CANCELADA' THEN 4
            END,
            COD_MOTORISTA
    FROM TB_VIAGEM

    WHERE DATA_PARTIDA BETWEEN @DATA_INICIAL AND @DATA_FINAL

    SET @DATA_INICIAL = @DATA_INICIAL + 1
END

EXEC SP_OLTP_VIAGEM '20240322', '20230101', '20240101'

SELECT * FROM TB_AUX_VIAGEM
