USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_OLTP_MOTORISTA (@DATA_CARGA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	SET LANGUAGE BRAZILIAN

	DELETE TB_AUX_MOTORISTA

	INSERT INTO TB_AUX_MOTORISTA
	SELECT @DATA_CARGA, M.COD_MOTORISTA, P.NOME, P.CPF, P.TELEFONE, M.NUMERO_DOCUMENTO, V.ID, V.PLACA
	FROM TB_MOTORISTA M INNER JOIN TB_PASSAGEIRO P
	ON M.ID_PASSAGEIRO = P.ID
	INNER JOIN TB_VEICULO V
	ON M.ID_PASSAGEIRO = V.ID_MOTORISTA_PASSAGEIRO
END

EXEC SP_OLTP_MOTORISTA '20240320'

SELECT * FROM TB_AUX_MOTORISTA

