USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_OLTP_MOTORISTA (@DATA_CARGA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	SET LANGUAGE BRAZILIAN

	INSERT INTO TB_AUX_MOTORISTA
	SELECT @DATA_CARGA, M.ID_PASSAGEIRO, P.NOME, P.CPF, P.TELEFONE, M.NUMERO_DOCUMENTO
	FROM TB_MOTORISTA M INNER JOIN TB_PASSAGEIRO P
	ON M.ID_PASSAGEIRO = P.ID
END

EXEC SP_OLTP_MOTORISTA '20240320'

SELECT * FROM TB_AUX_MOTORISTA

