USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_OLTP_VEICULO (@DATA_CARGA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	SET LANGUAGE BRAZILIAN

	INSERT INTO TB_AUX_VEICULO
	SELECT @DATA_CARGA, ID, RENAVAM, PLACA, DATA_EMISSAO, EXPEDIDOR, ESTADO
	FROM TB_VEICULO
END

EXEC SP_OLTP_VEICULO '20230320'

SELECT * FROM TB_AUX_VEICULO