USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_OLTP_VIAGEM (@DATA_CARGA DATETIME, @DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	SET LANGUAGE BRAZILIAN

	WHILE (@DATA_INICIAL < @DATA_FINAL)
	BEGIN
		INSERT INTO TB_AUX_VIAGEM
		SELECT @DATA_CARGA, V.DATA_PARTIDA, AL.COD_LOCAL, AUS.COD_STATUS_VIAGEM, V.ID_MOTORISTA, VE.ID, V.TOTAL_VAGAS, V.VALOR_PASSAGEM
		FROM TB_VIAGEM V INNER JOIN TB_VEICULO VE 
		ON V.ID_MOTORISTA = VE.ID_MOTORISTA_PASSAGEIRO
		INNER JOIN TB_

		-- TÁ ERRADA, FALTA FAZER 
	END
END