------------------------------- INDICADORES ----------------------------------------

-- 01. QUAL O NÚMERO DE VIAGENS CRIADAS HOJE?

SELECT SUM(FV.QUANTIDADE) 
AS NUMERO_DE_VIAGENS_CRIADAS FROM FATO_VIAGEM FV
INNER JOIN DIM_TEMPO DT 
ON FV.ID_DATA_DISPONIVEL = DT.ID_TEMPO
WHERE DT.DATA = CONVERT(DATE, GETDATE())

-- 02. QUAL O NÚMERO DE VIAGENS QUE PASSARAM PARA O STATUS 'CANCELADA' NO ÚLTIMO ANO?

SELECT SUM(FV.QUANTIDADE)
AS NUMERO_DE_VIAGENS_CANCELADAS FROM FATO_VIAGENS FV
INNER JOIN DIM_STATUS DS
ON FV.ID_STATUS = DS.ID_STATUS
INNER JOIN DIM_TEMPO DT
ON FV.ID_DATA_CANCELAMENTO = DT.ID_TEMPO
WHERE DS.STATUS = 'CANCELADA' AND YEAR(DT.DATA) = YEAR(GETDATE())-1

-- 03. QUAL O NÚMERO DE VIAGENS CRIADAS NO ÚLTIMO SEMESTRE? 

SELECT SUM(FV.QUANTIDADE) 
AS NUMERO_DE_VIAGENS_CRIADAS FROM FATO_VIAGEM FV
INNER JOIN DIM_TEMPO DT 
ON FV.ID_DATA_DISPONIVEL = DT.ID_TEMPO
WHERE DT.DATA >= DATEADD(MONTH, -6, CONVERT(DATE, GETDATE()))

-- 04. QUAL O NÚMERO DE VIAGENS CANCELADAS NO ÚLTIMO SEMESTRE?

SELECT SUM(FV.QUANTIDADE) 
AS NUMERO_DE_VIAGENS_CANCELADAS FROM FATO_VIAGEM FV
INNER JOIN DIM_STATUS DS
ON FV.ID_STATUS = DS.ID_STATUS
INNER JOIN DIM_TEMPO DT
ON FV.ID_DATA_CANCELAMENTO = DT.ID_TEMPO
WHERE DS.STATUS = 'CANCELADA' AND DT.DATA >= DATEADD(MONTH, -6, CONVERT(DATE, GETDATE()))

-- 05. QUAL O NÚMERO DE VIAGENS QUE PASSARAM PARA O STATUS 'CONFIRMADA' NO ÚLTIMO ANO?

SELECT SUM(FV.QUANTIDADE)
AS NUMERO_DE_VIAGENS_CONFIRMADAS FROM FATO_VIAGEM FV
INNER JOIN DIM_STATUS DS
ON FV.ID_STATUS = DS.ID_STATUS
INNER JOIN DIM_TEMPO DT
ON FV.ID_DATA_CONFIRMACAO = DT.ID_TEMPO
WHERE DS.STATUS = 'CONFIRMADA' AND YEAR(DT.DATA) = YEAR(GETDATE())-1

-- 06. QUANTAS VIAGENS FORAM CRIADAS COM O DESTINO 'ARACAJU' NO ÚLTIMO SEMESTRE?

SELECT SUM(FV.QUANTIDADE) 
AS NUMERO_DE_VIAGENS_CRIADAS FROM FATO_VIAGEM FV
INNER JOIN DIM_LOCAL DL
ON FV.ID_LOCAL_DESTINO = DL.ID_LOCAL
INNER JOIN DIM_TEMPO DT
ON FV.ID_DATA_DISPONIVEL = DT.ID_TEMPO
WHERE DL.LOCAL = 'ARACAJU' AND DT.DATA >= DATEADD(MONTH, -6, CONVERT(DATE, GETDATE()))

-- 07. QUANTAS VIAGENS FORAM CRIADAS COM O LOCAL DE ORIGEM 'ITABAIANA' NO ÚLTIMO SEMESTRE?

SELECT SUM(FV.QUANTIDADE) 
AS NUMERO_DE_VIAGENS_CRIADAS FROM FATO_VIAGEM FV
INNER JOIN DIM_LOCAL DL
ON FV.ID_LOCAL_ORIGEM = DL.ID_LOCAL
INNER JOIN DIM_TEMPO DT
ON FV.ID_DATA_DISPONIVEL = DT.ID_TEMPO
WHERE DL.LOCAL = 'ITABAIANA' AND DT.DATA >= DATEADD(MONTH, -6, CONVERT(DATE, GETDATE()))

-- 08. QUANTAS VIAGENS FORAM REALIZADAS COM A CAPACIDADE SUPERIOR À 30 PASSAGEIROS NO ÚLTIMO ANO? 

SELECT SUM(FV.QUANTIDADE)
AS NUMERO_DE_VIAGENS_REALIZADAS FROM FATO_VIAGEM FV
INNER JOIN DIM_STATUS DS 
ON FV.ID_STATUS = DS.ID_STATUS
INNER JOIN DIM_TEMPO DT
ON FV.ID_DATA_CONCLUIDA = DT.ID_TEMPO
WHERE DS.STATUS = 'CONCLUIDA' AND YEAR(DT.DATA) = YEAR(GETDATE())-1 AND FV.QUANTIDADE_DE_VAGAS > 30

-- 09. QUANTAS VIAGENS TIVERAM O VALOR DA PASSAGEM SUPERIOR À 30 REAIS NO ÚLTIMO ANO?

SELECT SUM(FV.QUANTIDADE)
AS NUMERO_DE_VIAGENS FROM FATO_VIAGEM FV
INNER JOIN DIM_STATUS DS 
ON FV.ID_STATUS = DS.ID_STATUS
INNER JOIN DIM_TEMPO DT
ON FV.ID_DATA_PAGAMENTO = DT.ID_TEMPO
WHERE DS.STATUS = 'DISPONIVEL' AND YEAR(DT.DATA) = YEAR(GETDATE())-1 AND FV.VALOR_PAGAMENTO > 30.00

-- 10. QUANTAS VIAGENS TIVERAM O VALOR DA PASSAGEM INFERIOR À 30 REAIS NO ÚLTIMO SEMESTRE?

SELECT SUM(FR.QUANTIDADE)
AS NUMERO_DE_VIAGENS FROM FATO_VIAGEM FV
INNER JOIN DIM_STATUS DS 
ON FV.ID_STATUS = DS.ID_STATUS
INNER JOIN DIM_TEMPO DT
ON FV.ID_DATA_PAGAMENTO = DT.ID_TEMPO
WHERE DS.STATUS = 'DISPONIVEL' AND DT.DATA >= DATEADD(MONTH, -6, CONVERT(DATE, GETDATE())) AND FV.VALOR_PAGAMENTO < 30.00
