USE Mais_Transporte

CREATE TABLE TB_AUX_LOCAL(
	DATA_CARGA DATETIME NOT NULL,
	LOCAL VARCHAR(45) NULL,
	COD_LOCAL INT NULL
)

CREATE TABLE TB_AUX_STATUS(
	DATA_CARGA DATETIME NOT NULL,
	Status VARCHAR(15) NOT NULL CHECK(STATUS IN ('DISPONIVEL', 'CONFIRMADA', 'CONCLUIDA', 'CANCELADA')),
	COD_STATUS INT NULL
)

CREATE TABLE TB_AUX_MOTORISTA(
	DATA_CARGA DATETIME NOT NULL,
	COD_MOTORISTA INT NULL,
	NOME VARCHAR(45) NULL,
	CPF VARCHAR(11) NULL,
	TELEFONE VARCHAR(15) NULL,
	CNH VARCHAR(15) NOT NULL UNIQUE
	COD_VEICULO INT NULL,
	PLACA VARCHAR(10) NOT NULL	
)

CREATE TABLE TB_AUX_VIAGEM(
	DATA_CARGA DATETIME NOT NULL,
	TITULO VARCHAR(50) NOT NULL,
	LOCAL_ORIGEM VARCHAR(50) NOT NULL,
	LOCAL_DESTINO VARCHAR(50) NOT NULL,
	VALOR_PASSAGEM NUMERIC(10,2) NOT NULL,
	TOTAL_VAGAS INT NOT NULL,
	DATA_PARTIDA DATETIME NOT NULL,
	DATA_CHEGADA DATETIME NOT NULL,
        DATA_DISPONIVEL DATE NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	STATUS VARCHAR(15) NOT NULL CHECK(STATUS IN ('DISPONIVEL', 'CONFIRMADA', 'CONCLUIDA', 'CANCELADA')),
	COD_MOTORISTA INT NOT NULL
)

CREATE INDEX IX_AUX_VIAGEM_DATA_CARGA ON TB_AUX_VIAGEM (DATA_CARGA)
