USE Mais_Transporte

CREATE TABLE TB_AUX_LOCAL(
	DATA_CARGA DATETIME NOT NULL,
	LOCAL VARCHAR(45) NULL,
	COD_LOCAL INT NULL
)

CREATE TABLE TB_AUX_STATUS(
	DATA_CARGA DATETIME NOT NULL,
	Status VARCHAR(15) NOT NULL CHECK(STATUS IN ('DISPONIVEL', 'CONFIRMADA', 'CONCLUIDA', 'CANCELADA')),
	COD_STATUS INT NULL
)

CREATE TABLE TB_AUX_MOTORISTA(
	DATA_CARGA DATETIME NOT NULL,
	COD_MOTORISTA INT NULL,
	NOME VARCHAR(45) NULL,
	CPF VARCHAR(11) NULL,
	TELEFONE VARCHAR(15) NULL,
	CNH VARCHAR(15) NOT NULL UNIQUE
)

CREATE TABLE TB_AUX_VEICULO(
	DATA_CARGA DATETIME NOT NULL,
	COD_VEICULO INT NULL,
	RENAVAM VARCHAR(15) NOT NULL,
	PLACA VARCHAR(10) NOT NULL,
	DATA_EMISSAO DATETIME NULL,
	EXPEDIDOR VARCHAR(5) NULL,
	ESTADO VARCHAR(2) NULL
)

CREATE TABLE TB_AUX_VIAGEM(
	DATA_CARGA DATETIME NOT NULL,
	DATA_VIAGEM DATETIME NULL,
	COD_LOCAL INT NULL,
	COD_STATUS_VIAGEM INT NULL,
	COD_MOTORISTA INT NULL,
	COD_VEICULO INT NULL,
	QUANTIDADE_VAGAS INT NULL,
	VALOR_PASSAGEM NUMERIC(10,2) NULL
)

CREATE INDEX IX_AUX_VIAGEM_DATA_CARGA ON TB_AUX_VIAGEM (DATA_CARGA)