USE Mais_Transporte

CREATE OR ALTER PROCEDURE SP_DIM_TEMPO (@DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
	SET NOCOUNT ON;
    SET LANGUAGE BRAZILIAN;
    DECLARE @DATA_ATUAL DATETIME = @DATA_INICIAL

    WHILE (@DATA_ATUAL <= @DATA_FINAL)
    BEGIN
        DECLARE @DIA INT = DAY(@DATA_ATUAL)
        DECLARE @DIA_SEMANA VARCHAR(50) = DATENAME(WEEKDAY, @DATA_ATUAL)
        DECLARE @FIM_SEMANA VARCHAR(3) = CASE WHEN DATENAME(WEEKDAY, @DATA_ATUAL) IN ('Sábado', 'Domingo') THEN 'SIM' ELSE 'NAO' END
        DECLARE @FERIADO VARCHAR(100)
        DECLARE @FL_FERIADO VARCHAR(3) = CASE WHEN @FERIADO IS NOT NULL THEN 'SIM' ELSE 'NAO' END
        DECLARE @MES INT = MONTH(@DATA_ATUAL)
        DECLARE @NOME_MES VARCHAR(100) = DATENAME(MONTH, @DATA_ATUAL)
        DECLARE @TRIMESTRE INT = (MONTH(@DATA_ATUAL) - 1) / 3 + 1
        DECLARE @NOME_TRIMESTRE VARCHAR(100) = 'Trimestre ' + CAST(@TRIMESTRE AS VARCHAR(2))
        DECLARE @SEMESTRE INT = (MONTH(@DATA_ATUAL) - 1) / 6 + 1
        DECLARE @NOME_SEMESTRE VARCHAR(100) = 'Semestre ' + CAST(@SEMESTRE AS VARCHAR(2))
        DECLARE @ANO INT = YEAR(@DATA_ATUAL)

        INSERT INTO DIM_TEMPO (NIVEL, DATA, DIA, DIA_SEMANA, FIM_SEMANA, FERIADO, FL_FERIADO, 
								MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO)
        VALUES ('DIA', @DATA_ATUAL, @DIA, @DIA_SEMANA, @FIM_SEMANA, @FERIADO, @FL_FERIADO, 
				@MES, @NOME_MES, @TRIMESTRE, @NOME_TRIMESTRE, @SEMESTRE, @NOME_SEMESTRE, @ANO)

        SET @DATA_ATUAL = DATEADD(DAY, 1, @DATA_ATUAL)
    END
END

EXEC SP_DIM_TEMPO '20230102', '20230201'

SELECT * FROM DIM_TEMPO

