USE Mais_Transporte

-- Procedimento para a dimensão tempo no nível dia
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO_DIA (@DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
	SET NOCOUNT ON
    SET LANGUAGE BRAZILIAN
    DECLARE @DATA_ATUAL DATETIME = @DATA_INICIAL

    WHILE (@DATA_ATUAL <= @DATA_FINAL)
    BEGIN
        DECLARE @DIA INT = DAY(@DATA_ATUAL)
        DECLARE @DIA_SEMANA VARCHAR(50) = DATENAME(WEEKDAY, @DATA_ATUAL)
        DECLARE @FIM_SEMANA VARCHAR(3) = CASE WHEN DATENAME(WEEKDAY, @DATA_ATUAL) IN ('Sábado', 'Domingo') THEN 'SIM' ELSE 'NAO' END
        DECLARE @FERIADO VARCHAR(100)
        DECLARE @FL_FERIADO VARCHAR(3) = CASE WHEN @FERIADO IS NOT NULL THEN 'SIM' ELSE 'NAO' END
        DECLARE @MES INT = MONTH(@DATA_ATUAL)
        DECLARE @NOME_MES VARCHAR(100) = DATENAME(MONTH, @DATA_ATUAL)
        DECLARE @TRIMESTRE INT = (MONTH(@DATA_ATUAL) - 1) / 3 + 1
        DECLARE @NOME_TRIMESTRE VARCHAR(100) = 'Trimestre ' + CAST(@TRIMESTRE AS VARCHAR(2))
        DECLARE @SEMESTRE INT = (MONTH(@DATA_ATUAL) - 1) / 6 + 1
        DECLARE @NOME_SEMESTRE VARCHAR(100) = 'Semestre ' + CAST(@SEMESTRE AS VARCHAR(2))
        DECLARE @ANO INT = YEAR(@DATA_ATUAL)

        INSERT INTO DIM_TEMPO (NIVEL, DATA, DIA, DIA_SEMANA, FIM_SEMANA, FERIADO, FL_FERIADO, 
								MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO)
        VALUES ('DIA', @DATA_ATUAL, @DIA, @DIA_SEMANA, @FIM_SEMANA, @FERIADO, @FL_FERIADO, 
				@MES, @NOME_MES, @TRIMESTRE, @NOME_TRIMESTRE, @SEMESTRE, @NOME_SEMESTRE, @ANO)

        SET @DATA_ATUAL = DATEADD(DAY, 1, @DATA_ATUAL)
    END
END

EXEC SP_DIM_TEMPO_DIA '20230101', '20240101'

-- Procedimento para a dimensão tempo no nível mês
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO_MES (@DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
    SET NOCOUNT ON
    SET LANGUAGE BRAZILIAN
    DECLARE @DATA_ATUAL DATETIME = @DATA_INICIAL

    WHILE (@DATA_ATUAL <= @DATA_FINAL)
    BEGIN
        DECLARE @MES INT = MONTH(@DATA_ATUAL)
        DECLARE @NOME_MES VARCHAR(100) = DATENAME(MONTH, @DATA_ATUAL)
		DECLARE @TRIMESTRE INT = (MONTH(@DATA_ATUAL) - 1) / 3 + 1 
        DECLARE @NOME_TRIMESTRE VARCHAR(100) = 'Trimestre ' + CAST(@TRIMESTRE AS VARCHAR(2))
        DECLARE @SEMESTRE INT = (MONTH(@DATA_ATUAL) - 1) / 6 + 1
        DECLARE @NOME_SEMESTRE VARCHAR(100) = 'Semestre ' + CAST(@SEMESTRE AS VARCHAR(2))
        DECLARE @ANO INT = YEAR(@DATA_ATUAL)

        INSERT INTO DIM_TEMPO (NIVEL, DATA, MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO)
        VALUES ('MES', @DATA_ATUAL, @MES, @NOME_MES, @TRIMESTRE, @NOME_TRIMESTRE, @SEMESTRE, @NOME_SEMESTRE, @ANO)

        SET @DATA_ATUAL = DATEADD(MONTH, 1, @DATA_ATUAL)
    END
END

EXEC SP_DIM_TEMPO_MES '20230101', '20240101'

-- Procedimento para a dimensão tempo no nível ano
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO_ANO (@DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
    SET NOCOUNT ON
    SET LANGUAGE BRAZILIAN
    DECLARE @DATA_ATUAL DATETIME = @DATA_INICIAL

    WHILE (@DATA_ATUAL <= @DATA_FINAL)
    BEGIN
        DECLARE @ANO INT = YEAR(@DATA_ATUAL)

        INSERT INTO DIM_TEMPO (NIVEL, DATA, ANO)
        VALUES ('ANO', @DATA_ATUAL, @ANO)

        SET @DATA_ATUAL = DATEADD(YEAR, 1, @DATA_ATUAL)
    END
END

EXEC SP_DIM_TEMPO_ANO '20230101', '20240101'

SELECT * FROM DIM_TEMPO


